### ISSUE TITLE
setBasePath() does not appear to do anything for SwaggerAssetBundle

### ISSUE THREAD

**Issue by jarrodhroberson** [paradoxical-io/dropwizard.swagger#1]
I want my swagger documentation to be under something other than the root context at `/`.

I tried passing in a `BeanConfig` with `.setBasePath("/docs/api")` and it does not appear to do anything. The swagger documentation is still hosted at `/`.

```
        bootstrap.addBundle(new SwaggerAssetsBundle(new Function<Environment, BeanConfig>()
        {
            @Override
            public BeanConfig apply(final Environment environment)
            {

                final BeanConfig config = new BeanConfig();
                config.setTitle("Shot In The Dark");
                config.setVersion("1.0.0");
                config.setResourcePackage("com.vertigrated.sitd.resource");
                config.setScan(true);
                config.setBasePath("/docs/api");
                return config;
            }
        }));
```

How do you specify where the main swagger page should be other than the root context?

**Comment by devshorts** [comment]
There's no way to do this right now without making your own resource page. However, give me a few hours and I'll push out a fix to support dynamically setting the base path :)

**Comment by devshorts** [comment]
A quick hotfix would be to subclass the swagger resource class and apply whatever pathing you want

**Comment by jakeswenson** [comment]
#2 is a proposed fix for this.

**Comment by devshorts** [comment]
The set base path in the swagger config is only there to tell the swagger api where your actual API lives at.  It doesn't affect where swagger itself lives at.

See the updated readme in master for how to override where the swagger endpoint will be.

**Comment by jakeswenson** [comment]
@jarrodhroberson have you tried the provided workaround? let us know if its working!

**Comment by jarrodhroberson** [comment]
I have not had time to try it, I will try this weekend when I work on my
project again.

On Thu, Feb 18, 2016 at 4:50 PM, Jake Swenson notifications@github.com
wrote:

> @jarrodhroberson https://github.com/jarrodhroberson have you tried the
> provided workaround? let us know if its working!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paradoxical-io/dropwizard.swagger/issues/1#issuecomment-185937001
> .

## 

Jarrod Roberson
678.551.2852
