### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by syoungblut** [paradoxical-io/dropwizard.swagger#11]
The documentation for admin port is misleading or out of date.

The class `AdminResourcesBundle`, does not seem to exist in your code base or maven package anymore. As a result, there is not enough information to configure the admin to have swagger.

The readme says

```
bootstrap.addBundle(
        AdminResourcesBundle.builder()
                            .swaggerUIConfigurator(SwaggerUIConfigurator.forConfig(env ->  config)));
```

but this doesn't compile as classes listed do not in fact exist

**Comment by jakeswenson** [comment]
@syoungblut fixed and updated documentation to show how to use the admin bundle in dropwizard-bundles and swagger. Also added a test case.
c8d4dd34b8f16f9c61c9a90ac9894863623dc5df
