### ISSUE TITLE
How do you set securityDefinition?

### ISSUE THREAD

**Issue by sunshineo** [paradoxical-io/dropwizard.swagger#14]
Like the one at the root level of
http://petstore.swagger.io/v2/swagger.json

Did you extend based on https://github.com/swagger-api/swagger-samples/tree/master/java/java-dropwizard ?

I searched there https://github.com/swagger-api/swagger-samples/search?p=1&q=securityDefinition&type=Code&utf8=%E2%9C%93 and saw securityDefinition settings but not in the dropwizard project.

BTW @jakeswenson I know you personally. We skied before. This is Gordon Sun

**Comment by devshorts** [comment]
Gordon, I'll let Jake comment since this is mostly his work but wanted to give you an FYI that he's out of the country right now and may not respond for a bit.

**Comment by sunshineo** [comment]
Thank you @devshorts 
Some more context. Since swagger-ui v2.2.0 , they changed the UI to dynamically show the auth button based on what the service say in the "securityDefinition".
For now, our UI just stuck at v2.1.8-M1

**Comment by jakeswenson** [comment]
Hey @sunshineo, Damn been a long time!
I'll look into this, thanks, i'll get back to you in a couple days

**Comment by jakeswenson** [comment]
@sunshineo I've committed a change with an example here: https://github.com/paradoxical-io/dropwizard.swagger/blob/master/src/test/java/io/paradoxical/dropwizard/swagger/sample/App.java#L73

I'm updating the swagger ui to `2.2.6` in another branch and then i'll release `dropwizard-swagger` `3.0`

**Comment by sunshineo** [comment]
Nice!
