### ISSUE TITLE
Publish 2.0 Version to maven central

### ISSUE THREAD

**Issue by woidda** [paradoxical-io/dropwizard.swagger#5]
Unfortunatly only the 1.2 version is available at maven central:
http://search.maven.org/#search%7Cga%7C1%7Cg%3Aio.paradoxical%20a%3Adropwizard-swagger

Could you please publish an updated version? Highly appreciated...

**Comment by devshorts** [comment]
@woidda I just pushed it out. Should be available soon

**Comment by jakeswenson** [comment]
@woidda `2.0` was intentionally not published yet as we were still baking it internally. Since we published it before it was ready, we have a PR out for `2.1` and some more clean up which **includes a breaking change**
This also fixes an issue with the wrong URI being used on the swagger page. #6

**Comment by jakeswenson** [comment]
@woidda 2.1 should be out thanks to @devshorts!
